<template>
  <va-sidebar
    :minimized="minimized"
    width="16rem"
    minimized-width="4rem"
    color="background-secondary"
    class="h-full border-r border-gray-200 dark:border-gray-800 flex flex-col"
  >
    <div class="flex-grow overflow-y-auto overflow-x-hidden">
        <va-sidebar-item
          v-for="item in navigationItems"
          :key="item.title"
          :active="isCurrentRoute(item.route)"
        >
          <Link :href="getRouteUrl(item.route)" class="w-full h-full flex items-center p-3 text-inherit decoration-0">
            <va-sidebar-item-content>
              <va-icon :name="item.icon" />
              <va-sidebar-item-title v-if="!minimized">{{ item.title }}</va-sidebar-item-title>
            </va-sidebar-item-content>
          </Link>
        </va-sidebar-item>
    </div>

    <div v-if="!minimized" class="p-4 mt-auto border-t border-gray-200 dark:border-gray-800">
       <span class="text-xs text-gray-500 font-bold font-mono uppercase">
          {{ $t('sidebar.role') }}: {{ displayRole }}
       </span>
    </div>
  </va-sidebar>
</template>

<script setup>
import { computed } from 'vue';
import { Link, usePage } from '@inertiajs/vue3';
import { useI18n } from 'vue-i18n';

defineProps({
  minimized: { type: Boolean, default: false },
});

const page = usePage();
const { t } = useI18n();

/**
 * Derives a fully localized human-readable string representing the current user's system role.
 * Accounts for structural inconsistencies in the role payload (e.g., Enum object vs raw string) 
 * and maps it dynamically to the corresponding translation namespace.
 * * @returns {string} The translated role name.
 */
const displayRole = computed(() => {
    const user = page.props.auth?.user;
    if (!user) return t('sidebar.roles.guest');
    
    const roleValue = typeof user.role === 'object' ? user.role.value : user.role;
    return t(`sidebar.roles.${roleValue.toLowerCase()}`) || roleValue;
});

/**
 * Constructs the primary navigation matrix dynamically.
 * Authorizes the user's access level to explicitly expose only permitted domain boundaries (routes).
 * Wrapping translation functions within a computed property enforces automatic sidebar re-renders on locale mutations.
 * * @returns {Array<Object>} The compiled list of authorized navigation items.
 */
const navigationItems = computed(() => {
  const user = page.props.auth?.user;
  if (!user) return [];
  
  const role = (typeof user.role === 'object' ? user.role.value : user.role).toLowerCase();

  const items = [
    { title: t('sidebar.dashboard'), icon: 'dashboard', route: 'dashboard' },
  ];

  if (role !== 'customer') {
    items.push({ 
        title: t('sidebar.time_tracking'), 
        icon: 'schedule', 
        route: 'work-sessions.index' 
    });
  }

  items.push({ title: t('sidebar.tickets'), icon: 'confirmation_number', route: 'tickets.index' });

  if (role === 'supporter' || role === 'admin') {
    items.push({ title: t('sidebar.users'), icon: 'group', route: 'users.index' });
    items.push({ title: t('sidebar.manage_tags'), icon: 'local_offer', route: 'tags.index' });
    items.push({ title: t('sidebar.vacations'), icon: 'event', route: 'vacations.index' });
  }

  if (role === 'admin') {
    items.push({ title: t('sidebar.teams'), icon: 'groups', route: 'teams.index' });
    items.push({ title: t('sidebar.activity_logs'), icon: 'history', route: 'activity-logs.index' });
  }

  return items;
});

/**
 * Resolves application paths safely to guarantee continuous stability.
 * Prevents fatal routing exceptions generated by Ziggy/Inertia if a referenced backend endpoint is temporarily missing.
 *
 * @param {string} routeName The internal identifier of the Laravel route.
 * @returns {string} The resolved full URL or a safe fallback anchor.
 */
const getRouteUrl = (routeName) => {
    try { return route(routeName); } catch { return '#'; }
};

/**
 * Verifies the active navigation context to trigger exact visual highlighting on the user interface.
 * Implements wildcard traversal logic to maintain the active state even inside deep child views (e.g. nested resources).
 *
 * @param {string} routeName The root boundary route name to match against the active HTTP request.
 * @returns {boolean} True if the browser's current location corresponds to the route's domain scope.
 */
const isCurrentRoute = (routeName) => {
  try {
    return route().current(routeName) || route().current(routeName.replace('.index', '.*'));
  } catch { return false; }
};
</script>